name: Python CI/CD

on:
  push:
    branches:
      - main  # Triggers the action on every push to the "main" branch
  pull_request:
    branches:
      - main  # Also runs when a pull request is made to the "main" branch

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out the code from your repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up the Python version
      with:
        python-version: '3.12'  # Use Python 3.12

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from the requirements.txt

    - name: Verify pytest-cov installation
      run: |
        pip show pytest-cov  # Verify that pytest-cov is installed

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run tests with coverage
      run: |
        pytest -v --cov=src tests/  # Run tests with coverage reporting

    - name: Run data preprocessing and model selection
      run: |
        python src/data_preprocessing.py  # Preprocessing step
        python src/model_selection.py  # Model selection and training