name: Python CI

on:
  push:
    branches:
      - main  # Triggers the action on every push to the "main" branch
  pull_request:
    branches:
      - main  # Also runs when a pull request is made to the "main" branch

jobs:
  build:

    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out the code from your repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up the Python version
      with:
        python-version: '3.12'  # Use Python 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from the requirements.txt

    - name: Run tests
      run: |
        pytest  # Run tests using pytest (adjust to your test framework)
      
    - name: Run data preprocessing and model selection
      run: |
        python src/data_preprocessing.py  # Preprocessing step
        python src/model_selection.py  # Model selection and training
